// Generated by LiveScript 1.4.0
(function(){
  var _, express, bodyParser, request, API_TOKEN, API_BASE, port, app, MESSAGES;
  _ = require('prelude-ls');
  express = require('express');
  bodyParser = require('body-parser');
  request = require('request');
  API_TOKEN = '00fd67af2a';
  API_BASE = 'https://dashboard.cash4code.net/score';
  port = 8080;
  app = express();
  app.use(bodyParser.json());
  MESSAGES = {};
  app.get('/', function(req, res){
    return res.send('Hello!');
  });
  app.post('/', function(req, res){
    var msgId, partNumber, totalParts, data, part, body;
    console.log("Body: " + JSON.stringify(req.body, null, 2));
    msgId = req.body.Id;
    partNumber = req.body.PartNumber;
    totalParts = req.body.TotalParts;
    data = req.body.Data;
    part = MESSAGES[msgId + ""];
    if (part === undefined) {
      part = {
        totalParts: totalParts,
        parts: []
      };
      part.parts[partNumber] = data;
      MESSAGES[msgId + ""] = part;
    }
    if (!in$(undefined, part)) {
      console.log("Got all parts for " + msgId + "...");
      body = _.Str.join('')(
      part.parts);
      console.log("Body: " + body);
      return request.post({
        url: API_BASE + '/' + msgId,
        body: body
      }, function(err, resp, body){
        return console.log("Response posted " + err);
      });
    }
  });
  app.listen(80, function(){
    return console.log("Unicorns app listening on port " + port);
  });
  function in$(x, xs){
    var i = -1, l = xs.length >>> 0;
    while (++i < l) if (x === xs[i]) return true;
    return false;
  }
}).call(this);
