// Generated by LiveScript 1.4.0
(function(){
  var _, express, bodyParser, request, Redis, API_TOKEN, API_BASE, port, redis, app, MESSAGES;
  _ = require('prelude-ls');
  express = require('express');
  bodyParser = require('body-parser');
  request = require('request');
  Redis = require('ioredis');
  API_TOKEN = '00fd67af2a';
  API_BASE = 'https://dashboard.cash4code.net/score';
  port = 8080;
  redis = new Redis({
    port: 6379,
    host: '127.0.0.1',
    family: 4,
    password: 'password',
    db: 0
  });
  app = express();
  app.use(bodyParser.json());
  MESSAGES = {};
  app.get('/', function(req, res){
    return res.send('Hello!');
  });
  app.post('/', function(req, res){
    var msgId, partNumber, totalParts, data, part, body;
    console.log("Body: " + JSON.stringify(req.body, null, 2));
    msgId = req.body.Id;
    partNumber = req.body.PartNumber;
    totalParts = req.body.TotalParts;
    data = req.body.Data;
    part = MESSAGES[msgId + ""];
    if (part === undefined) {
      part = {
        totalParts: totalParts,
        parts: []
      };
      part.parts[partNumber] = data;
      MESSAGES[msgId + ""] = part;
    }
    if (!in$(undefined, part)) {
      console.log("Got all parts for " + msgId + "...");
      body = _.Str.join('')(
      part.parts);
      console.log("Body: " + body);
      return request.post({
        url: API_BASE + '/' + msgId,
        headers: {
          "x-gameday-token": API_TOKEN
        },
        body: body
      }, function(err, resp, body){
        return console.log("Response posted " + err + " " + body);
      });
    }
  });
  app.listen(port, function(){
    return console.log("Unicorns app listening on port " + port);
  });
  function in$(x, xs){
    var i = -1, l = xs.length >>> 0;
    while (++i < l) if (x === xs[i]) return true;
    return false;
  }
}).call(this);
